"use client";

import { RefreshCw } from "lucide-react";
import { useParams } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { PageHeader } from "@/components/dashboard/page-header";
import { ProjectNav } from "@/components/project/project-nav";
import { CodeViewer } from "@/components/project/code-viewer";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { generateCode, getGeneratedFiles } from "@/lib/api";

export default function CodePage() {
  const { id } = useParams<{ id: string }>();
  const queryClient = useQueryClient();
  const files = useQuery({ queryKey: ["files", id], queryFn: () => getGeneratedFiles(id), retry: false });
  const generate = useMutation({ mutationFn: () => generateCode(id), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["files", id] }) });

  return (
    <>
      <ProjectNav projectId={id} active="Code" />
      <PageHeader
        title="Generated code"
        description="File tree and Monaco preview for the full-stack starter app generated by BuildOS agents."
        actions={
          <Button onClick={() => generate.mutate()} disabled={generate.isPending}>
            <RefreshCw className="h-4 w-4" aria-hidden />
            Regenerate code
          </Button>
        }
      />
      {files.data?.length ? (
        <CodeViewer files={files.data} />
      ) : (
        <EmptyState title="No generated files" description="Generate starter code for the frontend, backend, database, DevOps, and tests." action={<Button onClick={() => generate.mutate()}>Generate code</Button>} />
      )}
    </>
  );
}

